<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>About – HxH Gallery</title>
  <link rel="stylesheet" href="/styles.css" />
</head>
<body>

  <nav class="navbar">
    <ul class="nav-links">
      <li><a href="/character">Home</a></li>
      <li><a href="/about" class="active">About</a></li>
      <li><a href="/character/new">Add Character</a></li>
    </ul>
  </nav>

  <main class="about-page">

    <div class="about-hero">
      <h1>About This <span>Gallery</span></h1>
      <p class="about-sub">Why Hunter x Hunter?.</p>
    </div>

    <div class="about-body">

      <section class="about-block about-image-block">
        <img src="/images/anime.png" alt="Hunter x Hunter Anime" />


        <div class="about-text">
          <h2>Why Hunter x Hunter?</h2>
          <p>
            Hunter x Hunter, created by Yoshihiro Togashi, stands apart from nearly every other long-running shonen manga. Where most series rely on escalating power fantasies, HxH changes the genre its protagonists frequently lose, its villains receive empathetic arcs, and its way of showcasing power through nen, rewards cleverness over raw strength. It is, put simply, the most thoughtfully and beautifully constructed battle manga ever written.
          </p>
          <p>
            This gallery was built to celebrate five characters who each represent a different dimension of that complexit as well as my most favorite characters in the anime: the pure-hearted optimist Gon, the trained killer reclaiming his humanity Killua, the beautiful chaos and complex agent Hisoka, the quietly fierce loyalist Palm, and the philosophical crime boss Chrollo. Together they cover nearly the full moral and emotional spectrum the series explores.
          </p>

        </div>
      </section>

    </div>

  </main>

</body>
</html>