spring.application.name=HxH
spring.datasource.url=jdbc:postgresql://ep-lively-mud-adat8tfz-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_D6XdBULY2iTr&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update
#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

